{"info": {"author": "Sebastian Kreft", "author_email": "UNKNOWN", "bugtrack_url": null, "classifiers": ["Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: Python Software Foundation License", "Programming Language :: Python :: 2.6"], "description": "backport_collections\n====================\n\n.. image:: https://badge.fury.io/py/backport_collections.png\n    :target: http://badge.fury.io/py/backport_collections\n\n.. image:: https://travis-ci.org/sk-/backport_collections.png?branch=master\n    :target: https://travis-ci.org/sk-/backport_collections\n\n.. image:: https://coveralls.io/repos/sk-/backport_collections/badge.png?branch=master\n    :target: https://coveralls.io/r/sk-/backport_collections?branch=master\n\nbackport_collections is a backport of Python 2.7's ``collections`` module for Python 2.6.\n\nWhat is backported?\n-------------------\n\n``Counter``, ``deque``, ``OrderedDict`` and ``namedtuple`` are backported.\nThe rest of the members of the ``collections`` module are still exposed. Note\nthough that some ``ABC`` classes are slighlty different (see known issues below).\n\nUsage\n-----\n\nTo use it just import the desired classes from the module ``backport_collections``.\nExample::\n\n    from backport_collections import Counter\n    from backport_collections import deque\n    from backport_collections import OrderedDict\n    from backport_collections import namedtuple\n\nKnown Issues\n------------\n\n* In Python 2.6 Issue 9137 is not fixed as it complains if it gets a keyword\n  argument named ``self``. The error is ``TypeError: update() got multiple values for keyword argument 'self'``.\n  Additionally the keyword argument cannot be called ``other`` either as it will think it is the full dict. No error is raised in this case.\n\n* In Python 2.6 Issue 8743 is not fully fixed: Set interoperability with real sets\n\n\nLicense\n-------\n\nThe Python Software Foundation License.\n\nChanges\n-------\n\n* v0.1 (15/08/2014): Synced to revision http://hg.python.org/cpython/rev/6d41f139709b", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "http://github.com/sk-/backport_collections", "keywords": null, "license": "UNKNOWN", "maintainer": null, "maintainer_email": null, "name": "backport_collections", "package_url": "https://pypi.org/project/backport_collections/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/backport_collections/", "project_urls": {"Download": "UNKNOWN", "Homepage": "http://github.com/sk-/backport_collections"}, "release_url": "https://pypi.org/project/backport_collections/0.1/", "requires_dist": null, "requires_python": null, "summary": "Backport of Python 2.7's collections module", "version": "0.1", "yanked": false, "html_description": "<div class=\"project-description\">\n            <a href=\"http://badge.fury.io/py/backport_collections\" rel=\"nofollow\"><img alt=\"https://badge.fury.io/py/backport_collections.png\" src=\"https://warehouse-camo.ingress.cmh1.psfhosted.org/68ca6021fdec1ab58b08f3020ee45395cc2b1942/68747470733a2f2f62616467652e667572792e696f2f70792f6261636b706f72745f636f6c6c656374696f6e732e706e67\"></a>\n<a href=\"https://travis-ci.org/sk-/backport_collections\" rel=\"nofollow\"><img alt=\"https://travis-ci.org/sk-/backport_collections.png?branch=master\" src=\"https://warehouse-camo.ingress.cmh1.psfhosted.org/2602b104bc16d38f024867b09c73df777bfd33d6/68747470733a2f2f7472617669732d63692e6f72672f736b2d2f6261636b706f72745f636f6c6c656374696f6e732e706e673f6272616e63683d6d6173746572\"></a>\n<a href=\"https://coveralls.io/r/sk-/backport_collections?branch=master\" rel=\"nofollow\"><img alt=\"https://coveralls.io/repos/sk-/backport_collections/badge.png?branch=master\" src=\"https://warehouse-camo.ingress.cmh1.psfhosted.org/d5fef9cbb1adfb04176dcd59af73253db36e3d34/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f736b2d2f6261636b706f72745f636f6c6c656374696f6e732f62616467652e706e673f6272616e63683d6d6173746572\"></a>\n<p>backport_collections is a backport of Python 2.7\u2019s <tt>collections</tt> module for Python 2.6.</p>\n<div id=\"what-is-backported\">\n<h2>What is backported?</h2>\n<p><tt>Counter</tt>, <tt>deque</tt>, <tt>OrderedDict</tt> and <tt>namedtuple</tt> are backported.\nThe rest of the members of the <tt>collections</tt> module are still exposed. Note\nthough that some <tt>ABC</tt> classes are slighlty different (see known issues below).</p>\n</div>\n<div id=\"usage\">\n<h2>Usage</h2>\n<p>To use it just import the desired classes from the module <tt>backport_collections</tt>.\nExample:</p>\n<pre>from backport_collections import Counter\nfrom backport_collections import deque\nfrom backport_collections import OrderedDict\nfrom backport_collections import namedtuple\n</pre>\n</div>\n<div id=\"known-issues\">\n<h2>Known Issues</h2>\n<ul>\n<li>In Python 2.6 Issue 9137 is not fixed as it complains if it gets a keyword\nargument named <tt>self</tt>. The error is <tt>TypeError: update() got multiple values for keyword argument 'self'</tt>.\nAdditionally the keyword argument cannot be called <tt>other</tt> either as it will think it is the full dict. No error is raised in this case.</li>\n<li>In Python 2.6 Issue 8743 is not fully fixed: Set interoperability with real sets</li>\n</ul>\n</div>\n<div id=\"license\">\n<h2>License</h2>\n<p>The Python Software Foundation License.</p>\n</div>\n<div id=\"changes\">\n<h2>Changes</h2>\n<ul>\n<li>v0.1 (15/08/2014): Synced to revision <a href=\"http://hg.python.org/cpython/rev/6d41f139709b\" rel=\"nofollow\">http://hg.python.org/cpython/rev/6d41f139709b</a></li>\n</ul>\n</div>\n\n          </div>"}, "last_serial": 1208988, "releases": {"0.1": [{"comment_text": "", "digests": {"md5": "b4cb1ede168fc9cb7d4f59399a15fbca", "sha256": "939ac17313c6cda524b15fea9706af6ececd07b763a48b371b5b6d345b05eab7"}, "downloads": -1, "filename": "backport_collections-0.1.tar.gz", "has_sig": false, "md5_digest": "b4cb1ede168fc9cb7d4f59399a15fbca", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 37704, "upload_time": "2014-09-01T09:47:50", "upload_time_iso_8601": "2014-09-01T09:47:50.279752Z", "url": "https://files.pythonhosted.org/packages/d0/dd/d833f666d54a3ec27a8ffd85e2c05838585550de3b38addd8a11d8528734/backport_collections-0.1.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "b4cb1ede168fc9cb7d4f59399a15fbca", "sha256": "939ac17313c6cda524b15fea9706af6ececd07b763a48b371b5b6d345b05eab7"}, "downloads": -1, "filename": "backport_collections-0.1.tar.gz", "has_sig": false, "md5_digest": "b4cb1ede168fc9cb7d4f59399a15fbca", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 37704, "upload_time": "2014-09-01T09:47:50", "upload_time_iso_8601": "2014-09-01T09:47:50.279752Z", "url": "https://files.pythonhosted.org/packages/d0/dd/d833f666d54a3ec27a8ffd85e2c05838585550de3b38addd8a11d8528734/backport_collections-0.1.tar.gz", "yanked": false}], "timestamp": "Thu May  7 18:15:08 2020"}