{"info": {"author": "Patrick Robertshaw", "author_email": "patrick.robertshaw1@gmail.com", "bugtrack_url": null, "classifiers": ["Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3", "Topic :: Software Development :: Build Tools"], "description": "[![CircleCI](https://circleci.com/gh/Cruuncher/EasyExceptions/tree/master.svg?style=shield)](https://circleci.com/gh/Cruuncher/EasyExceptions/tree/master) \n[![Coverage Status](https://coveralls.io/repos/github/Cruuncher/EasyExceptions/badge.svg?branch=master)](https://coveralls.io/github/Cruuncher/EasyExceptions?branch=master)\n[![PyPi](https://img.shields.io/badge/pypi-v1.0.2-blue)](https://pypi.org/project/easy-exceptions/1.0.2/)\n\n# EasyExceptions\nThrow and catch named exceptions without creating a class first. The goal of this project is to make working with named exceptions simpler. It's often a huge overhead of work to create named exceptions in a separate file before being able to throw them to nicely be caught. \n\n## Installation \n\n    pip install easy-exceptions\n\n## Usage\n    from easy_exceptions import EasyException\n    try:\n        raise EasyException('NamedException')('TEST MESSAGE')\n    except EasyException('NamedException') as e:\n        print(\"Caught this specific exception without having to define it!\")\n\nEasyExceptions even supports using a custom parent class instead of the base Exception. This is because APIs often use a custom exception class for rendering error messages. All you have to do in this case is pass that parent class to EasyException and instantiate it the way you always would. For example: \n\n    from easy_exceptions import EasyException \n    from api.exceptions import BaseException # Your custom base exception\n    try:\n        # you can pass whatever special args here that you usually do to BaseException\n        raise EasyException('NamedException', parent=BaseException)(...)\n    except EasyException('NamedException', parent=BaseException):\n        print(\"Caught the specific exception!\") \n    # This exception can still be caught by referencing the BaseException with regular syntax \n    except BaseException:\n        print(\"This would be called if the above exception handler wasn't there\")\n\nThis can be further simplified by binding the BaseException during application startup using the bind_parent\n\n    from easy_exceptions import EasyException, bind_parent \n    from api.exceptions import BaseException\n\n    bind_parent(BaseException)\n    try:\n        raise EasyException('NamedException') \n    except BaseException: #Could alse use EasyException('NamedException') to target the named exception only\n        print(\"Exceptions are always of type BaseException now\")", "description_content_type": "text/markdown", "docs_url": null, "download_url": "https://github.com/Cruuncher/EasyExceptions/archive/1.0.2.tar.gz", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://github.com/Cruuncher/EasyExceptions", "keywords": "exceptions", "license": "MIT", "maintainer": "", "maintainer_email": "", "name": "easy-exceptions", "package_url": "https://pypi.org/project/easy-exceptions/", "platform": "", "project_url": "https://pypi.org/project/easy-exceptions/", "project_urls": {"Download": "https://github.com/Cruuncher/EasyExceptions/archive/1.0.2.tar.gz", "Homepage": "https://github.com/Cruuncher/EasyExceptions"}, "release_url": "https://pypi.org/project/easy-exceptions/1.0.2/", "requires_dist": null, "requires_python": "", "summary": "Throw and catch named exceptions without creating a class first", "version": "1.0.2", "yanked": false, "html_description": "<div class=\"project-description\">\n            <p><a href=\"https://circleci.com/gh/Cruuncher/EasyExceptions/tree/master\" rel=\"nofollow\"><img alt=\"CircleCI\" src=\"https://warehouse-camo.ingress.cmh1.psfhosted.org/317a81cdb63913dccbd8c971187731260661778e/68747470733a2f2f636972636c6563692e636f6d2f67682f437275756e636865722f45617379457863657074696f6e732f747265652f6d61737465722e7376673f7374796c653d736869656c64\"></a>\n<a href=\"https://coveralls.io/github/Cruuncher/EasyExceptions?branch=master\" rel=\"nofollow\"><img alt=\"Coverage Status\" src=\"https://warehouse-camo.ingress.cmh1.psfhosted.org/fb584c53420891568ddfad79ce73bc5f387d040e/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f437275756e636865722f45617379457863657074696f6e732f62616467652e7376673f6272616e63683d6d6173746572\"></a>\n<a href=\"https://pypi.org/project/easy-exceptions/1.0.2/\" rel=\"nofollow\"><img alt=\"PyPi\" src=\"https://warehouse-camo.ingress.cmh1.psfhosted.org/d8fc871d5009ff5ee32bf287e70a624d1c76e043/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f707970692d76312e302e322d626c7565\"></a></p>\n<h1>EasyExceptions</h1>\n<p>Throw and catch named exceptions without creating a class first. The goal of this project is to make working with named exceptions simpler. It's often a huge overhead of work to create named exceptions in a separate file before being able to throw them to nicely be caught.</p>\n<h2>Installation</h2>\n<pre><code>pip install easy-exceptions\n</code></pre>\n<h2>Usage</h2>\n<pre><code>from easy_exceptions import EasyException\ntry:\n    raise EasyException('NamedException')('TEST MESSAGE')\nexcept EasyException('NamedException') as e:\n    print(\"Caught this specific exception without having to define it!\")\n</code></pre>\n<p>EasyExceptions even supports using a custom parent class instead of the base Exception. This is because APIs often use a custom exception class for rendering error messages. All you have to do in this case is pass that parent class to EasyException and instantiate it the way you always would. For example:</p>\n<pre><code>from easy_exceptions import EasyException \nfrom api.exceptions import BaseException # Your custom base exception\ntry:\n    # you can pass whatever special args here that you usually do to BaseException\n    raise EasyException('NamedException', parent=BaseException)(...)\nexcept EasyException('NamedException', parent=BaseException):\n    print(\"Caught the specific exception!\") \n# This exception can still be caught by referencing the BaseException with regular syntax \nexcept BaseException:\n    print(\"This would be called if the above exception handler wasn't there\")\n</code></pre>\n<p>This can be further simplified by binding the BaseException during application startup using the bind_parent</p>\n<pre><code>from easy_exceptions import EasyException, bind_parent \nfrom api.exceptions import BaseException\n\nbind_parent(BaseException)\ntry:\n    raise EasyException('NamedException') \nexcept BaseException: #Could alse use EasyException('NamedException') to target the named exception only\n    print(\"Exceptions are always of type BaseException now\")\n</code></pre>\n\n          </div>"}, "last_serial": 6764961, "releases": {"0.1.0": [{"comment_text": "", "digests": {"md5": "c2783f02b91da0d2f6306ed25e19bc78", "sha256": "75fada46c5c620eb28efffc29ee311f9de8b46333dc5206ec7a41210639a47ec"}, "downloads": -1, "filename": "easy_exceptions-0.1.0.tar.gz", "has_sig": false, "md5_digest": "c2783f02b91da0d2f6306ed25e19bc78", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1245, "upload_time": "2020-03-05T22:13:06", "upload_time_iso_8601": "2020-03-05T22:13:06.309706Z", "url": "https://files.pythonhosted.org/packages/2c/bb/d54fc711c9895963720bb90822a660f3caa855ba48c98c19b4e59daee90d/easy_exceptions-0.1.0.tar.gz", "yanked": false}], "0.1.1": [{"comment_text": "", "digests": {"md5": "5b0d92661c82b8fa98f6a8795a34c848", "sha256": "6727a22f63bef65b9d5767834756f5d1c8f2194372ec2d27a0443872d6d8b043"}, "downloads": -1, "filename": "easy_exceptions-0.1.1.tar.gz", "has_sig": false, "md5_digest": "5b0d92661c82b8fa98f6a8795a34c848", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2169, "upload_time": "2020-03-06T11:53:23", "upload_time_iso_8601": "2020-03-06T11:53:23.762291Z", "url": "https://files.pythonhosted.org/packages/86/61/beca49ef1ded8f1959e272a5a48c95fb0b31d7cd4439bae511bdecfecb43/easy_exceptions-0.1.1.tar.gz", "yanked": false}], "1.0.0": [{"comment_text": "", "digests": {"md5": "b64b46bc2d169a110f000ec8f873cd33", "sha256": "3966eb3c0b54ff4bb4cd1a350cd8eec7f792f2a1f10c4dd65533223b2c2282d1"}, "downloads": -1, "filename": "easy_exceptions-1.0.0.tar.gz", "has_sig": false, "md5_digest": "b64b46bc2d169a110f000ec8f873cd33", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2299, "upload_time": "2020-03-06T16:09:09", "upload_time_iso_8601": "2020-03-06T16:09:09.602547Z", "url": "https://files.pythonhosted.org/packages/73/ac/1c3b0a94d3a18f27e92e1a2e2897122109131a7b5cf365111828d8aaa7b6/easy_exceptions-1.0.0.tar.gz", "yanked": false}], "1.0.1": [{"comment_text": "", "digests": {"md5": "2c55e6520d10cc1e44a0a0308c532765", "sha256": "d9bba9571498c4e6c28f4f7dd091d01aef0afbfebf0de127ae59c7f125ac898d"}, "downloads": -1, "filename": "easy_exceptions-1.0.1.tar.gz", "has_sig": false, "md5_digest": "2c55e6520d10cc1e44a0a0308c532765", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2509, "upload_time": "2020-03-06T16:15:18", "upload_time_iso_8601": "2020-03-06T16:15:18.878839Z", "url": "https://files.pythonhosted.org/packages/ba/e8/b2f43a9fd0ceddd9e2f8d6db06ffe0452e299f442947681b7de715a26e21/easy_exceptions-1.0.1.tar.gz", "yanked": false}], "1.0.2": [{"comment_text": "", "digests": {"md5": "6c77abc60ac0f777ef83cc0270f2bd14", "sha256": "4bcb54d9acee8a9cc5afd96acf3a7e858108d55038efddb7279671f4f579bb6a"}, "downloads": -1, "filename": "easy_exceptions-1.0.2.tar.gz", "has_sig": false, "md5_digest": "6c77abc60ac0f777ef83cc0270f2bd14", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2665, "upload_time": "2020-03-06T22:04:22", "upload_time_iso_8601": "2020-03-06T22:04:22.671656Z", "url": "https://files.pythonhosted.org/packages/b9/a0/a111c7792d8bd6d5c97d1d55738d6ff364b351b8ed992cb1f70cb2f9e2f7/easy_exceptions-1.0.2.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "6c77abc60ac0f777ef83cc0270f2bd14", "sha256": "4bcb54d9acee8a9cc5afd96acf3a7e858108d55038efddb7279671f4f579bb6a"}, "downloads": -1, "filename": "easy_exceptions-1.0.2.tar.gz", "has_sig": false, "md5_digest": "6c77abc60ac0f777ef83cc0270f2bd14", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2665, "upload_time": "2020-03-06T22:04:22", "upload_time_iso_8601": "2020-03-06T22:04:22.671656Z", "url": "https://files.pythonhosted.org/packages/b9/a0/a111c7792d8bd6d5c97d1d55738d6ff364b351b8ed992cb1f70cb2f9e2f7/easy_exceptions-1.0.2.tar.gz", "yanked": false}], "timestamp": "Fri May  8 00:48:23 2020"}