{"info": {"author": "PokestarFan", "author_email": "pokestarfan@yahoo.com", "bugtrack_url": null, "classifiers": [], "description": "UNKNOWN\n\n\n", "description_content_type": null, "docs_url": null, "download_url": "", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://github.com/Poketec/ExceptionGenerator", "keywords": "", "license": "MIT", "maintainer": "", "maintainer_email": "", "name": "exceptiongenerator", "package_url": "https://pypi.org/project/exceptiongenerator/", "platform": "", "project_url": "https://pypi.org/project/exceptiongenerator/", "project_urls": {"Homepage": "https://github.com/Poketec/ExceptionGenerator"}, "release_url": "https://pypi.org/project/exceptiongenerator/2.3/", "requires_dist": null, "requires_python": "", "summary": "Easy way to generate exceptions that just have a message", "version": "2.3", "yanked": false, "html_description": "<div class=\"project-description\">\n            <p>UNKNOWN</p>\n\n          </div>"}, "last_serial": 3527850, "releases": {"1.0": [{"comment_text": "", "digests": {"md5": "8b9e5d7e973eee96203e372b685c1400", "sha256": "c2a7a95b1c81c9b7d9f3fbe83cdc37de4f1982c02cfd8e47040f9a89a3666b23"}, "downloads": -1, "filename": "exceptiongenerator-1.0-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "8b9e5d7e973eee96203e372b685c1400", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 2491, "upload_time": "2018-01-25T21:46:20", "upload_time_iso_8601": "2018-01-25T21:46:20.972074Z", "url": "https://files.pythonhosted.org/packages/51/61/519895a3ba6b77bfa5829574a344bc571ce865cfcdbdfd53738d430a1cb2/exceptiongenerator-1.0-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "d5bce0d57de750b043ae5a8411b844ee", "sha256": "e5de6947f83bc746000c1bcb7f79eedd9b972cd15b5c65340dedab0a09fb8a4c"}, "downloads": -1, "filename": "exceptiongenerator-1.0-py3.6.egg", "has_sig": false, "md5_digest": "d5bce0d57de750b043ae5a8411b844ee", "packagetype": "bdist_egg", "python_version": "3.6", "requires_python": null, "size": 1719, "upload_time": "2018-01-25T21:46:22", "upload_time_iso_8601": "2018-01-25T21:46:22.285677Z", "url": "https://files.pythonhosted.org/packages/43/21/a5a0f5f21d190896a2e349e49c2a10b1efdff4627724fc346acbadbbdcdc/exceptiongenerator-1.0-py3.6.egg", "yanked": false}, {"comment_text": "", "digests": {"md5": "a5f45882a775b9b452ad803fd026597f", "sha256": "57630492e808428f60b120ba983f6811e88abe02776064786a2962c4adb84aee"}, "downloads": -1, "filename": "exceptiongenerator-1.0.tar.gz", "has_sig": false, "md5_digest": "a5f45882a775b9b452ad803fd026597f", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1015, "upload_time": "2018-01-25T21:46:24", "upload_time_iso_8601": "2018-01-25T21:46:24.053054Z", "url": "https://files.pythonhosted.org/packages/43/08/fcccb1612b3b86688f2cbf6ad3ca9223785eaa8044273c629970119a1922/exceptiongenerator-1.0.tar.gz", "yanked": false}], "2.0": [{"comment_text": "", "digests": {"md5": "fff2ab63ce72ab154818871ca678e854", "sha256": "04c625ce446b5d3edceffc0c239e88aa0138ea488c09f6cb86ddf2365d7612b0"}, "downloads": -1, "filename": "exceptiongenerator-2.0-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "fff2ab63ce72ab154818871ca678e854", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 2542, "upload_time": "2018-01-26T02:03:23", "upload_time_iso_8601": "2018-01-26T02:03:23.878030Z", "url": "https://files.pythonhosted.org/packages/09/2b/6c49bc7a080ec36854aa165e5821051c3bc411cfd83834ab63674387262c/exceptiongenerator-2.0-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "ddf6b9df4af27d9cfbcda23ed3c85147", "sha256": "fc8732c0ab592b5eba5dbe40076c686e05d971360ecdea5e95f004d38e536564"}, "downloads": -1, "filename": "exceptiongenerator-2.0-py3.6.egg", "has_sig": false, "md5_digest": "ddf6b9df4af27d9cfbcda23ed3c85147", "packagetype": "bdist_egg", "python_version": "3.6", "requires_python": null, "size": 1840, "upload_time": "2018-01-26T02:03:24", "upload_time_iso_8601": "2018-01-26T02:03:24.563672Z", "url": "https://files.pythonhosted.org/packages/35/ea/c5783af0d69f6768612e714a2330cae496211fa43a7e921a7e3a2adad277/exceptiongenerator-2.0-py3.6.egg", "yanked": false}, {"comment_text": "", "digests": {"md5": "c27469638c03de7bbd90a15364b484a2", "sha256": "4c7062b5e5d2e5f647bd9fa5c838aef95afbe3b3298902fb2a8e3d92792cfa55"}, "downloads": -1, "filename": "exceptiongenerator-2.0.tar.gz", "has_sig": false, "md5_digest": "c27469638c03de7bbd90a15364b484a2", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1090, "upload_time": "2018-01-26T02:03:25", "upload_time_iso_8601": "2018-01-26T02:03:25.376732Z", "url": "https://files.pythonhosted.org/packages/40/f6/b20842c5e0e39c25d2b6fdb07fb444ed54241faea2d55b100c9fe3a97dd4/exceptiongenerator-2.0.tar.gz", "yanked": false}], "2.1": [{"comment_text": "", "digests": {"md5": "250460a34c3249e580cfcff4c08cfb8b", "sha256": "750146ee999f533162b053398508b1495348e1021471849d170eb692d9c56819"}, "downloads": -1, "filename": "exceptiongenerator-2.1-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "250460a34c3249e580cfcff4c08cfb8b", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 2581, "upload_time": "2018-01-26T23:41:14", "upload_time_iso_8601": "2018-01-26T23:41:14.531397Z", "url": "https://files.pythonhosted.org/packages/d7/f6/a15685042036f582759862568a76792d110856b6006e9ae5332b58f20403/exceptiongenerator-2.1-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "a1d516fadaf664830e60d66431e14a27", "sha256": "880b62ba445e77ccc9ecf5fc53bbf43a3230176e4b0b8be5638afc553a4e9a15"}, "downloads": -1, "filename": "exceptiongenerator-2.1-py3.6.egg", "has_sig": false, "md5_digest": "a1d516fadaf664830e60d66431e14a27", "packagetype": "bdist_egg", "python_version": "3.6", "requires_python": null, "size": 1956, "upload_time": "2018-01-26T23:41:15", "upload_time_iso_8601": "2018-01-26T23:41:15.435447Z", "url": "https://files.pythonhosted.org/packages/03/30/273a4af8e0371e104d0dd43f4d56f4f4923645f8e6d0ebb0a9027e74dab5/exceptiongenerator-2.1-py3.6.egg", "yanked": false}, {"comment_text": "", "digests": {"md5": "d6ef201b4fb1a6d715c35a3048f5e7ad", "sha256": "952ea9e0ed03c78ecccd74f2b25c6e50cdef4355bfc6d477c5d5cc0efb1f60af"}, "downloads": -1, "filename": "exceptiongenerator-2.1.tar.gz", "has_sig": false, "md5_digest": "d6ef201b4fb1a6d715c35a3048f5e7ad", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1128, "upload_time": "2018-01-26T23:41:16", "upload_time_iso_8601": "2018-01-26T23:41:16.846042Z", "url": "https://files.pythonhosted.org/packages/27/32/1030a622e5e40960092866aeffd95529e91349c723646812773a0b387026/exceptiongenerator-2.1.tar.gz", "yanked": false}], "2.2": [{"comment_text": "", "digests": {"md5": "4fb047b0a4f8cfd39cf21c4481cd7ba0", "sha256": "9c553aaef1bac54a1e8fcbe7ad3bb6887b25e738dd57a1d99a034d5ed4fc2fa7"}, "downloads": -1, "filename": "exceptiongenerator-2.2-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "4fb047b0a4f8cfd39cf21c4481cd7ba0", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 2549, "upload_time": "2018-01-27T03:07:21", "upload_time_iso_8601": "2018-01-27T03:07:21.102864Z", "url": "https://files.pythonhosted.org/packages/b3/b5/b4989286833441a84c61874f95a879a62d634168cae66e97576b5140e8b0/exceptiongenerator-2.2-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "21e28bffd90218a9f28cee89b4448e19", "sha256": "243656a2505084b45583b885c5b7aef711233a6be48734e3b2f88913ea48aeea"}, "downloads": -1, "filename": "exceptiongenerator-2.2-py3.6.egg", "has_sig": false, "md5_digest": "21e28bffd90218a9f28cee89b4448e19", "packagetype": "bdist_egg", "python_version": "3.6", "requires_python": null, "size": 1947, "upload_time": "2018-01-27T03:07:22", "upload_time_iso_8601": "2018-01-27T03:07:22.281235Z", "url": "https://files.pythonhosted.org/packages/3d/21/4117cffa65ae544a575698d0cdf5d019731330ea44bc3c7ecb5f5adf2ca2/exceptiongenerator-2.2-py3.6.egg", "yanked": false}, {"comment_text": "", "digests": {"md5": "e80e376c6974222f020d9898ae5a0025", "sha256": "dfbec1a5bcf805f227010960f7c2a5f9992fdb3c54ed462e1d3fd3f95e02d2ad"}, "downloads": -1, "filename": "exceptiongenerator-2.2.tar.gz", "has_sig": false, "md5_digest": "e80e376c6974222f020d9898ae5a0025", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1082, "upload_time": "2018-01-27T03:07:23", "upload_time_iso_8601": "2018-01-27T03:07:23.285090Z", "url": "https://files.pythonhosted.org/packages/4c/37/5b2df3b27eacc80c22e28a91e11ffb17574a34f9ede64767f3b588eb0c12/exceptiongenerator-2.2.tar.gz", "yanked": false}], "2.3": [{"comment_text": "", "digests": {"md5": "2810abe44abed38ea172be48fecaa3d6", "sha256": "c7676dd0275309926ede81875c79b68072c4d05177e95578dd0e72cc2b819790"}, "downloads": -1, "filename": "exceptiongenerator-2.3-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "2810abe44abed38ea172be48fecaa3d6", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 2560, "upload_time": "2018-01-28T00:05:32", "upload_time_iso_8601": "2018-01-28T00:05:32.363913Z", "url": "https://files.pythonhosted.org/packages/f8/52/999d967e0b4974402f68a3a6f5fc37467ebb613cbf69fb163428640afff1/exceptiongenerator-2.3-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "4f4c372d3b113295946b141e6ffe0ea1", "sha256": "a2aaae3b2ce91d0f3aeed2dc390a11a0e0b14bafd7d7e8c2289bb2c5830fe941"}, "downloads": -1, "filename": "exceptiongenerator-2.3-py3.6.egg", "has_sig": false, "md5_digest": "4f4c372d3b113295946b141e6ffe0ea1", "packagetype": "bdist_egg", "python_version": "3.6", "requires_python": null, "size": 1952, "upload_time": "2018-01-28T00:05:35", "upload_time_iso_8601": "2018-01-28T00:05:35.375654Z", "url": "https://files.pythonhosted.org/packages/89/69/49571cf0fd57568b0f0c8cdbbe0240b2376ee4f6e87d9ae662ba2e3b9746/exceptiongenerator-2.3-py3.6.egg", "yanked": false}, {"comment_text": "", "digests": {"md5": "4afc01cc38850f9cd7df883e0f91da64", "sha256": "f525ea044932b3fb95d9b5264be4e18d1c5d7ccfc4daea9bdf47f87095d46994"}, "downloads": -1, "filename": "exceptiongenerator-2.3.tar.gz", "has_sig": false, "md5_digest": "4afc01cc38850f9cd7df883e0f91da64", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1084, "upload_time": "2018-01-28T00:05:36", "upload_time_iso_8601": "2018-01-28T00:05:36.360885Z", "url": "https://files.pythonhosted.org/packages/db/aa/7974334115360c94209dc65cf81295e434de0d8bfa795724d482ca9a06f0/exceptiongenerator-2.3.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "2810abe44abed38ea172be48fecaa3d6", "sha256": "c7676dd0275309926ede81875c79b68072c4d05177e95578dd0e72cc2b819790"}, "downloads": -1, "filename": "exceptiongenerator-2.3-py2.py3-none-any.whl", "has_sig": false, "md5_digest": "2810abe44abed38ea172be48fecaa3d6", "packagetype": "bdist_wheel", "python_version": "py2.py3", "requires_python": null, "size": 2560, "upload_time": "2018-01-28T00:05:32", "upload_time_iso_8601": "2018-01-28T00:05:32.363913Z", "url": "https://files.pythonhosted.org/packages/f8/52/999d967e0b4974402f68a3a6f5fc37467ebb613cbf69fb163428640afff1/exceptiongenerator-2.3-py2.py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "4f4c372d3b113295946b141e6ffe0ea1", "sha256": "a2aaae3b2ce91d0f3aeed2dc390a11a0e0b14bafd7d7e8c2289bb2c5830fe941"}, "downloads": -1, "filename": "exceptiongenerator-2.3-py3.6.egg", "has_sig": false, "md5_digest": "4f4c372d3b113295946b141e6ffe0ea1", "packagetype": "bdist_egg", "python_version": "3.6", "requires_python": null, "size": 1952, "upload_time": "2018-01-28T00:05:35", "upload_time_iso_8601": "2018-01-28T00:05:35.375654Z", "url": "https://files.pythonhosted.org/packages/89/69/49571cf0fd57568b0f0c8cdbbe0240b2376ee4f6e87d9ae662ba2e3b9746/exceptiongenerator-2.3-py3.6.egg", "yanked": false}, {"comment_text": "", "digests": {"md5": "4afc01cc38850f9cd7df883e0f91da64", "sha256": "f525ea044932b3fb95d9b5264be4e18d1c5d7ccfc4daea9bdf47f87095d46994"}, "downloads": -1, "filename": "exceptiongenerator-2.3.tar.gz", "has_sig": false, "md5_digest": "4afc01cc38850f9cd7df883e0f91da64", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1084, "upload_time": "2018-01-28T00:05:36", "upload_time_iso_8601": "2018-01-28T00:05:36.360885Z", "url": "https://files.pythonhosted.org/packages/db/aa/7974334115360c94209dc65cf81295e434de0d8bfa795724d482ca9a06f0/exceptiongenerator-2.3.tar.gz", "yanked": false}], "timestamp": "Fri May  8 00:44:53 2020"}