{"info": {"author": "hassaku", "author_email": "hassaku.apps@gmail.com", "bugtrack_url": null, "classifiers": [], "description": "[![Build Status](https://travis-ci.org/hassaku/exception-slacker.png)](https://travis-ci.org/hassaku/exception-slacker)\n\n# Install\n\n```\n$ pip install exception-slacker\n```\n\n# Usage\n\n## When ENV set\n\n```\nimport os\nimport exception_slacker\n\nos.environ['EXCEPTION_SLACKER_TOKEN'] = \"XXXXXXXXXX\"\nos.environ['EXCEPTION_SLACKER_CHANNEL'] = \"#notification-test\"\nos.environ['EXCEPTION_SLACKER_NAME'] = \"Exception Notifier\"\n\nraise StandardError(\"ERROR\")\n```\n\n![screenshot](https://raw.githubusercontent.com/hassaku/exception-slacker/master/screenshot.png)\n\n## When ENV not set\n\n```\nimport exception_slacker\n\nraise StandardError(\"ERROR\")\n```\n\n```\nError in sys.excepthook:\nTraceback (most recent call last):\n  File \"/path/to/exception_slacker.py\", line 17, in notification\n    raise StandardError(\"exception_slacker is imported, but %s aren't found in ENV.\" % ','.join(__KEYS))\nStandardError: exception_slacker is imported, but EXCEPTION_SLACKER_TOKEN,EXCEPTION_SLACKER_CHANNEL,EXCEPTION_SLACKER_NAME aren't found in ENV.\n\nOriginal exception was:\nTraceback (most recent call last):\n  File \"test.py\", line 20, in <module>\n    raise StandardError(\"ERROR\")\nStandardError: ERROR\n```\n\n# Update PyPI\n\n```\n$ nosetests -vs\n$ python setup.py register  # if necessary\n$ python setup.py sdist upload\n```\n\n# Contributing\n\n- Fork the repository on Github\n- Create a named feature branch (like add_component_x)\n- Write your change\n- Write tests for your change (if applicable)\n- Run the tests, ensuring they all pass\n- Submit a Pull Request using Github\n\n# License\n\nMIT", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://github.com/hassaku/exception_slacker", "keywords": "slack exception", "license": "MIT", "maintainer": null, "maintainer_email": null, "name": "exception-slacker", "package_url": "https://pypi.org/project/exception-slacker/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/exception-slacker/", "project_urls": {"Download": "UNKNOWN", "Homepage": "https://github.com/hassaku/exception_slacker"}, "release_url": "https://pypi.org/project/exception-slacker/0.1.1/", "requires_dist": null, "requires_python": null, "summary": "Notify exceptions on slack", "version": "0.1.1", "yanked": false, "html_description": "<div class=\"project-description\">\n            [![Build Status](https://travis-ci.org/hassaku/exception-slacker.png)](https://travis-ci.org/hassaku/exception-slacker)<br><br># Install<br><br>```<br>$ pip install exception-slacker<br>```<br><br># Usage<br><br>## When ENV set<br><br>```<br>import os<br>import exception_slacker<br><br>os.environ['EXCEPTION_SLACKER_TOKEN'] = \"XXXXXXXXXX\"<br>os.environ['EXCEPTION_SLACKER_CHANNEL'] = \"#notification-test\"<br>os.environ['EXCEPTION_SLACKER_NAME'] = \"Exception Notifier\"<br><br>raise StandardError(\"ERROR\")<br>```<br><br>![screenshot](https://raw.githubusercontent.com/hassaku/exception-slacker/master/screenshot.png)<br><br>## When ENV not set<br><br>```<br>import exception_slacker<br><br>raise StandardError(\"ERROR\")<br>```<br><br>```<br>Error in sys.excepthook:<br>Traceback (most recent call last):<br>  File \"/path/to/exception_slacker.py\", line 17, in notification<br>    raise StandardError(\"exception_slacker is imported, but %s aren't found in ENV.\" % ','.join(__KEYS))<br>StandardError: exception_slacker is imported, but EXCEPTION_SLACKER_TOKEN,EXCEPTION_SLACKER_CHANNEL,EXCEPTION_SLACKER_NAME aren't found in ENV.<br><br>Original exception was:<br>Traceback (most recent call last):<br>  File \"test.py\", line 20, in &lt;module&gt;<br>    raise StandardError(\"ERROR\")<br>StandardError: ERROR<br>```<br><br># Update PyPI<br><br>```<br>$ nosetests -vs<br>$ python setup.py register  # if necessary<br>$ python setup.py sdist upload<br>```<br><br># Contributing<br><br>- Fork the repository on Github<br>- Create a named feature branch (like add_component_x)<br>- Write your change<br>- Write tests for your change (if applicable)<br>- Run the tests, ensuring they all pass<br>- Submit a Pull Request using Github<br><br># License<br><br>MIT\n          </div>"}, "last_serial": 1979717, "releases": {"0.1.0": [{"comment_text": "", "digests": {"md5": "e9cf4a5668e9ab99bd9ca89a9ed91046", "sha256": "b01cf12fb91e0a95817b84afbd85d7d393cadd3028badb230d097111d733dea0"}, "downloads": -1, "filename": "exception-slacker-0.1.0.tar.gz", "has_sig": false, "md5_digest": "e9cf4a5668e9ab99bd9ca89a9ed91046", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2158, "upload_time": "2016-02-27T15:06:15", "upload_time_iso_8601": "2016-02-27T15:06:15.800911Z", "url": "https://files.pythonhosted.org/packages/9b/d1/c2c3e8ca0da39b58af82b878b6d6023d44ff41ca7e3f7ce877f9464b1fd6/exception-slacker-0.1.0.tar.gz", "yanked": false}], "0.1.1": [{"comment_text": "", "digests": {"md5": "259d151de4ec5492f931dcac85254bbe", "sha256": "88658664307806ed55166b869d12a751d349d4cb3c104ff036136e75e298738f"}, "downloads": -1, "filename": "exception-slacker-0.1.1.tar.gz", "has_sig": false, "md5_digest": "259d151de4ec5492f931dcac85254bbe", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2320, "upload_time": "2016-02-27T15:34:24", "upload_time_iso_8601": "2016-02-27T15:34:24.966163Z", "url": "https://files.pythonhosted.org/packages/6b/1b/1e9a5e99df5a286029d66c3af11950f47e5b66e6318673a7166f7581dfa9/exception-slacker-0.1.1.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "259d151de4ec5492f931dcac85254bbe", "sha256": "88658664307806ed55166b869d12a751d349d4cb3c104ff036136e75e298738f"}, "downloads": -1, "filename": "exception-slacker-0.1.1.tar.gz", "has_sig": false, "md5_digest": "259d151de4ec5492f931dcac85254bbe", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2320, "upload_time": "2016-02-27T15:34:24", "upload_time_iso_8601": "2016-02-27T15:34:24.966163Z", "url": "https://files.pythonhosted.org/packages/6b/1b/1e9a5e99df5a286029d66c3af11950f47e5b66e6318673a7166f7581dfa9/exception-slacker-0.1.1.tar.gz", "yanked": false}], "timestamp": "Fri May  8 00:44:53 2020"}