{"info": {"author": "Plone Security Team", "author_email": "security@plone.org", "bugtrack_url": null, "classifiers": ["Framework :: Plone", "Programming Language :: Python"], "description": "Plone hotfix, 2013-12-10\r\n========================\r\n\r\nThis hotfix fixes multiple minor vulnerabilities in Plone. This hotfix fixes\r\nissues in all versions of Plone.\r\n\r\nThe hotfix is officially supported by the Plone security team on the\r\nfollowing versions of Plone in accordance with the Plone\r\n`version support policy`_: 4.3.2, 4.3.1, 4.3, 4.2.6, 4.1.6, 4.0.9 and 3.3.6.\r\n\r\nThe fixes included here will be incorporated into subsequent releases of Plone,\r\nso Plone 4.3.3 and greater should not require this hotfix.\r\n\r\n\r\nInstallation\r\n============\r\n\r\nInstallation instructions can be found at\r\nhttps://plone.org/security/20131210\r\n\r\n\r\nQ&A\r\n===\r\n\r\nQ: How can I confirm that the hotfix is installed correctly and my site is protected?\r\n  A: On startup, the hotfix will log a number of messages to the Zope event log\r\n  that look like this::\r\n\r\n    2013-12-10 15:00:00 INFO Products.PloneHotfix20131210 Applied catalog patch\r\n\r\n  The exact list of patches attempted depends on the version of Plone.\r\n  If a patch is attempted but fails, it will be logged as a warning that says\r\n  \"Could not apply\". This may indicate that you have a non-standard Plone\r\n  installation.\r\n\r\nQ: I am using an unsupported version of Plone and this hotfix breaks my\r\ninstance, what should I do? \r\n  A: If at all possible, upgrade to a supported\r\n  version of Plone. Otherwise, comment out individual fixes from __init__.py\r\n  until the error ceases. Please let security@plone.org know of any problems, as\r\n  they may be specific advice available for problems.\r\n\r\nQ: How can I report problems installing the patch?\r\n  A: Contact the Plone security team at security@plone.org, or visit the\r\n  #plone channel on freenode IRC.\r\n\r\nQ: How can I report other potential security vulnerabilities?\r\n  A: Please email the security team at security@plone.org rather than discussing\r\n  potential security issues publicly.\r\n\r\n.. _`version support policy`: http://plone.org/support/version-support-policy\r\n\r\nChangelog\r\n=========\r\n\r\n1.0 (unreleased)\r\n----------------\r\n\r\n - Initial release", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "http://github.com/plone", "keywords": "plone security hotfix patch", "license": "GPL", "maintainer": "", "maintainer_email": "", "name": "Products.PloneHotfix20131210", "package_url": "https://pypi.org/project/Products.PloneHotfix20131210/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/Products.PloneHotfix20131210/", "project_urls": {"Download": "UNKNOWN", "Homepage": "http://github.com/plone"}, "release_url": "https://pypi.org/project/Products.PloneHotfix20131210/1.0/", "requires_dist": null, "requires_python": null, "summary": "Various Plone hotfixes, 2013-12-10", "version": "1.0", "yanked": false, "html_description": "<div class=\"project-description\">\n            Plone hotfix, 2013-12-10\n<br>========================\n<br>\n<br>This hotfix fixes multiple minor vulnerabilities in Plone. This hotfix fixes\n<br>issues in all versions of Plone.\n<br>\n<br>The hotfix is officially supported by the Plone security team on the\n<br>following versions of Plone in accordance with the Plone\n<br>`version support policy`_: 4.3.2, 4.3.1, 4.3, 4.2.6, 4.1.6, 4.0.9 and 3.3.6.\n<br>\n<br>The fixes included here will be incorporated into subsequent releases of Plone,\n<br>so Plone 4.3.3 and greater should not require this hotfix.\n<br>\n<br>\n<br>Installation\n<br>============\n<br>\n<br>Installation instructions can be found at\n<br>https://plone.org/security/20131210\n<br>\n<br>\n<br>Q&amp;A\n<br>===\n<br>\n<br>Q: How can I confirm that the hotfix is installed correctly and my site is protected?\n<br>  A: On startup, the hotfix will log a number of messages to the Zope event log\n<br>  that look like this::\n<br>\n<br>    2013-12-10 15:00:00 INFO Products.PloneHotfix20131210 Applied catalog patch\n<br>\n<br>  The exact list of patches attempted depends on the version of Plone.\n<br>  If a patch is attempted but fails, it will be logged as a warning that says\n<br>  \"Could not apply\". This may indicate that you have a non-standard Plone\n<br>  installation.\n<br>\n<br>Q: I am using an unsupported version of Plone and this hotfix breaks my\n<br>instance, what should I do? \n<br>  A: If at all possible, upgrade to a supported\n<br>  version of Plone. Otherwise, comment out individual fixes from __init__.py\n<br>  until the error ceases. Please let security@plone.org know of any problems, as\n<br>  they may be specific advice available for problems.\n<br>\n<br>Q: How can I report problems installing the patch?\n<br>  A: Contact the Plone security team at security@plone.org, or visit the\n<br>  #plone channel on freenode IRC.\n<br>\n<br>Q: How can I report other potential security vulnerabilities?\n<br>  A: Please email the security team at security@plone.org rather than discussing\n<br>  potential security issues publicly.\n<br>\n<br>.. _`version support policy`: http://plone.org/support/version-support-policy\n<br>\n<br>Changelog\n<br>=========\n<br>\n<br>1.0 (unreleased)\n<br>----------------\n<br>\n<br> - Initial release\n          </div>"}, "last_serial": 2071794, "releases": {"1.0": [{"comment_text": "", "digests": {"md5": "f1febcdf21d0ad84f97407aa9cc2f4e8", "sha256": "e161b4f80af85a0808d56a03a8391d787c607f41fe79d34a22e45ecf9e39443e"}, "downloads": -1, "filename": "Products.PloneHotfix20131210-1.0.tar.gz", "has_sig": false, "md5_digest": "f1febcdf21d0ad84f97407aa9cc2f4e8", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 11886, "upload_time": "2013-12-10T14:58:11", "upload_time_iso_8601": "2013-12-10T14:58:11.582539Z", "url": "https://files.pythonhosted.org/packages/12/22/062684a479a7f6eeb0d2a3da04d5a2c9245ec06ca5f17cb821f7f8179828/Products.PloneHotfix20131210-1.0.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "f1febcdf21d0ad84f97407aa9cc2f4e8", "sha256": "e161b4f80af85a0808d56a03a8391d787c607f41fe79d34a22e45ecf9e39443e"}, "downloads": -1, "filename": "Products.PloneHotfix20131210-1.0.tar.gz", "has_sig": false, "md5_digest": "f1febcdf21d0ad84f97407aa9cc2f4e8", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 11886, "upload_time": "2013-12-10T14:58:11", "upload_time_iso_8601": "2013-12-10T14:58:11.582539Z", "url": "https://files.pythonhosted.org/packages/12/22/062684a479a7f6eeb0d2a3da04d5a2c9245ec06ca5f17cb821f7f8179828/Products.PloneHotfix20131210-1.0.tar.gz", "yanked": false}], "timestamp": "Fri May  8 03:17:59 2020"}