{"info": {"author": "Benjamin Hedrich", "author_email": "benjamin.hedrich@pagenotfound.de", "bugtrack_url": null, "classifiers": ["Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: Implementation :: CPython", "Programming Language :: Python :: Implementation :: PyPy", "Topic :: Software Development :: Libraries", "Topic :: Utilities"], "description": "Uncatchable Exception\n====================\n.. image:: https://badge.fury.io/py/uncatchable-exception.png\n   :target: http://badge.fury.io/py/uncatchable-exception\n.. image:: https://pypip.in/d/uncatchable-exception/badge.png\n   :target: https://crate.io/packages/uncatchable-exception/\n.. image:: https://requires.io/github/bh/uncatchable-exception/requirements.png?branch=master\n   :target: https://requires.io/github/bh/uncatchable-exception/requirements/?branch=master\n\nDescription\n-----------\n\nYou will get an exception class which is not catchable when it was raised.\n\nInstallation\n------------\n\nUse ``pip`` to install:\n\n.. code:: bash\n\n    $ pip install uncatchable-exception --use-mirrors\n\nUsage\n-----\n\nAn example:\n\n.. code:: python\n\n    from uncatchable_exception import UncatchableException\n\n    def raise_an_uncatchable_exception():\n        raise UncatchableException('Harr Harr!')\n\n    try:\n        raise_an_uncatchable_exception()\n    except:\n        print(\"Uncatchable exception caught\")\n\n\nYeah, the Python process is hanging, kill it with ``^C``", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://github.com/bh/uncatchable-exception", "keywords": null, "license": "BSD", "maintainer": null, "maintainer_email": null, "name": "uncatchable-exception", "package_url": "https://pypi.org/project/uncatchable-exception/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/uncatchable-exception/", "project_urls": {"Download": "UNKNOWN", "Homepage": "https://github.com/bh/uncatchable-exception"}, "release_url": "https://pypi.org/project/uncatchable-exception/0.1.2/", "requires_dist": null, "requires_python": null, "summary": "An exception class which is not catchable when it was raised.", "version": "0.1.2", "yanked": false, "html_description": "<div class=\"project-description\">\n            Uncatchable Exception<br>====================<br>.. image:: https://badge.fury.io/py/uncatchable-exception.png<br>   :target: http://badge.fury.io/py/uncatchable-exception<br>.. image:: https://pypip.in/d/uncatchable-exception/badge.png<br>   :target: https://crate.io/packages/uncatchable-exception/<br>.. image:: https://requires.io/github/bh/uncatchable-exception/requirements.png?branch=master<br>   :target: https://requires.io/github/bh/uncatchable-exception/requirements/?branch=master<br><br>Description<br>-----------<br><br>You will get an exception class which is not catchable when it was raised.<br><br>Installation<br>------------<br><br>Use ``pip`` to install:<br><br>.. code:: bash<br><br>    $ pip install uncatchable-exception --use-mirrors<br><br>Usage<br>-----<br><br>An example:<br><br>.. code:: python<br><br>    from uncatchable_exception import UncatchableException<br><br>    def raise_an_uncatchable_exception():<br>        raise UncatchableException('Harr Harr!')<br><br>    try:<br>        raise_an_uncatchable_exception()<br>    except:<br>        print(\"Uncatchable exception caught\")<br><br><br>Yeah, the Python process is hanging, kill it with ``^C``\n          </div>"}, "last_serial": 1087854, "releases": {"0.1.2": [{"comment_text": "", "digests": {"md5": "f3a5e866ddba510680ba77cee8108820", "sha256": "122c7bcd6c73f392d7dd7994cf61d00e03a8d4192fc761239d47b302aedffe72"}, "downloads": -1, "filename": "uncatchable_exception-0.1.2-py34-none-any.whl", "has_sig": false, "md5_digest": "f3a5e866ddba510680ba77cee8108820", "packagetype": "bdist_wheel", "python_version": "3.4", "requires_python": null, "size": 3366, "upload_time": "2014-05-10T12:25:58", "upload_time_iso_8601": "2014-05-10T12:25:58.558270Z", "url": "https://files.pythonhosted.org/packages/af/02/c5de2aa64c64058a57aa6961f51b10dcf107a5b4a06fa2ce0d6fdfdca5ed/uncatchable_exception-0.1.2-py34-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "74549e153c09edc2b357194eb36d4930", "sha256": "91944bfc760827ae6f5a95a8fd5aca5c26126bb10b136cdf696ead1a9ae2ab50"}, "downloads": -1, "filename": "uncatchable-exception-0.1.2.tar.bz2", "has_sig": false, "md5_digest": "74549e153c09edc2b357194eb36d4930", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2011, "upload_time": "2014-05-10T12:25:47", "upload_time_iso_8601": "2014-05-10T12:25:47.904991Z", "url": "https://files.pythonhosted.org/packages/34/87/2598e5d514359329941ef61d2a3ef4a56d5c2018237cff4578a4581a9943/uncatchable-exception-0.1.2.tar.bz2", "yanked": false}, {"comment_text": "", "digests": {"md5": "ed8265b1873d2703eca064bacaf81aee", "sha256": "625be1ee3696ae2a1b8456c76c7c743eb097002af6af4e00f3a1ee1007ba15dd"}, "downloads": -1, "filename": "uncatchable-exception-0.1.2.tar.gz", "has_sig": false, "md5_digest": "ed8265b1873d2703eca064bacaf81aee", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1774, "upload_time": "2014-05-10T12:25:55", "upload_time_iso_8601": "2014-05-10T12:25:55.080327Z", "url": "https://files.pythonhosted.org/packages/f2/18/e4b063af087d4962cac6e87ee82e2718ebe19217c09328b9f7b75e473bb7/uncatchable-exception-0.1.2.tar.gz", "yanked": false}, {"comment_text": "", "digests": {"md5": "7fd8359a034d0acee4ac52e3548dab16", "sha256": "d098556f1785229bf0fae90d3e618e770d6664a9706d9a6ffb45c7aad77bc2d0"}, "downloads": -1, "filename": "uncatchable-exception-0.1.2.zip", "has_sig": false, "md5_digest": "7fd8359a034d0acee4ac52e3548dab16", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 4522, "upload_time": "2014-05-10T12:25:51", "upload_time_iso_8601": "2014-05-10T12:25:51.874934Z", "url": "https://files.pythonhosted.org/packages/b7/b4/20482dd1fe6d0817fd6da2e58edad02542b324bcf14841dfb86f542e807f/uncatchable-exception-0.1.2.zip", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "f3a5e866ddba510680ba77cee8108820", "sha256": "122c7bcd6c73f392d7dd7994cf61d00e03a8d4192fc761239d47b302aedffe72"}, "downloads": -1, "filename": "uncatchable_exception-0.1.2-py34-none-any.whl", "has_sig": false, "md5_digest": "f3a5e866ddba510680ba77cee8108820", "packagetype": "bdist_wheel", "python_version": "3.4", "requires_python": null, "size": 3366, "upload_time": "2014-05-10T12:25:58", "upload_time_iso_8601": "2014-05-10T12:25:58.558270Z", "url": "https://files.pythonhosted.org/packages/af/02/c5de2aa64c64058a57aa6961f51b10dcf107a5b4a06fa2ce0d6fdfdca5ed/uncatchable_exception-0.1.2-py34-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "74549e153c09edc2b357194eb36d4930", "sha256": "91944bfc760827ae6f5a95a8fd5aca5c26126bb10b136cdf696ead1a9ae2ab50"}, "downloads": -1, "filename": "uncatchable-exception-0.1.2.tar.bz2", "has_sig": false, "md5_digest": "74549e153c09edc2b357194eb36d4930", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 2011, "upload_time": "2014-05-10T12:25:47", "upload_time_iso_8601": "2014-05-10T12:25:47.904991Z", "url": "https://files.pythonhosted.org/packages/34/87/2598e5d514359329941ef61d2a3ef4a56d5c2018237cff4578a4581a9943/uncatchable-exception-0.1.2.tar.bz2", "yanked": false}, {"comment_text": "", "digests": {"md5": "ed8265b1873d2703eca064bacaf81aee", "sha256": "625be1ee3696ae2a1b8456c76c7c743eb097002af6af4e00f3a1ee1007ba15dd"}, "downloads": -1, "filename": "uncatchable-exception-0.1.2.tar.gz", "has_sig": false, "md5_digest": "ed8265b1873d2703eca064bacaf81aee", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1774, "upload_time": "2014-05-10T12:25:55", "upload_time_iso_8601": "2014-05-10T12:25:55.080327Z", "url": "https://files.pythonhosted.org/packages/f2/18/e4b063af087d4962cac6e87ee82e2718ebe19217c09328b9f7b75e473bb7/uncatchable-exception-0.1.2.tar.gz", "yanked": false}, {"comment_text": "", "digests": {"md5": "7fd8359a034d0acee4ac52e3548dab16", "sha256": "d098556f1785229bf0fae90d3e618e770d6664a9706d9a6ffb45c7aad77bc2d0"}, "downloads": -1, "filename": "uncatchable-exception-0.1.2.zip", "has_sig": false, "md5_digest": "7fd8359a034d0acee4ac52e3548dab16", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 4522, "upload_time": "2014-05-10T12:25:51", "upload_time_iso_8601": "2014-05-10T12:25:51.874934Z", "url": "https://files.pythonhosted.org/packages/b7/b4/20482dd1fe6d0817fd6da2e58edad02542b324bcf14841dfb86f542e807f/uncatchable-exception-0.1.2.zip", "yanked": false}], "timestamp": "Fri May  8 03:40:58 2020"}