{"info": {"author": "Thierry Florac", "author_email": "tflorac@ulthar.net", "bugtrack_url": null, "classifiers": ["Development Status :: 4 - Beta", "Framework :: Zope3", "License :: OSI Approved :: Zope Public License", "Programming Language :: Python", "Topic :: Software Development :: Libraries :: Python Modules"], "description": "====================\n        ztfy.monitor package\n        ====================\n        \n        .. contents::\n        \n        What is ztfy.monitor ?\n        ======================\n        \n        ztfy.monitor is a small monitor for Zope 3, using zc.z3monitor as base package.\n        It adds a \"threads\" command to monitoring console, to see what the Zope server is\n        actually doing, even when all threads are busy and the server can't respond to any request.\n        \n        It's actually useful when your server is not performing as well as you would like, is eating\n        all your CPU time or is waiting in a deadlock loop.\n        \n        It's main code is based on DeadlockDebugger, developed by Nuxeo for the Zope2 application\n        server.\n        \n        \n        How to use ztfy.monitor ?\n        =========================\n        \n        This package can be used via the zc.monitor NGI server ; read the configuration of this package to see how it is configured.\n        \n        Go on by including ztfy.monitor package into your application configuration : ::\n        \n        \t<include package=\"ztfy.monitor\" />\n        \n        After that and as soon as the monitoring server is launched, you can connect and\n        use the \"threads\" command to see threads activity ; for example, by using the \"netcat\"\n        application on a monitor running on port 8081 : ::\n        \n        \t$ echo \"threads\" | nc localhost 8081\n        \tThreads traceback dump at 2008-11-03 21:50:46\n        \n        \tThread -1210468160:\n        \t  File \"./bin/paster\", line 151, in ?\n        \t    paste.script.command.run()\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteScript-1.6.2-py2.4.egg/paste/script/command.py\", line 79, in run\n        \t    invoke(command, command_name, options, args[1:])\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteScript-1.6.2-py2.4.egg/paste/script/command.py\", line 118, in invoke\n        \t    exit_code = runner.run(args)\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteScript-1.6.2-py2.4.egg/paste/script/command.py\", line 213, in run\n        \t    result = self.command()\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteScript-1.6.2-py2.4.egg/paste/script/serve.py\", line 257, in command\n        \t    server(app)\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteDeploy-1.3.1-py2.4.egg/paste/deploy/loadwsgi.py\", line 139, in server_wrapper\n        \t    wsgi_app, context.global_conf,\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteDeploy-1.3.1-py2.4.egg/paste/deploy/util/fixtypeerror.py\", line 57, in fix_call\n        \t    val = callable(*args, **kw)\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1314, in server_runner\n        \t    serve(wsgi_app, **kwargs)\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1282, in serve\n        \t    server.serve_forever()\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1066, in serve_forever\n        \t    self.handle_request()\n        \t  File \"/usr/lib/python2.4/SocketServer.py\", line 217, in handle_request\n        \t    request, client_address = self.get_request()\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1100, in get_request\n        \t    (conn,info) = SecureHTTPServer.get_request(self)\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 378, in get_request\n        \t    (conn, info) = self.socket.accept()\n        \t  File \"/usr/lib/python2.4/socket.py\", line 161, in accept\n        \t    sock, addr = self._sock.accept()\n        \t\n        \tThread -1303708784:\n        \t  File \"/usr/lib/python2.4/threading.py\", line 442, in __bootstrap\n        \t    self.run()\n        \t  File \"/usr/lib/python2.4/threading.py\", line 422, in run\n        \t    self.__target(*self.__args, **self.__kwargs)\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 851, in worker_thread_callback\n        \t    runnable = self.queue.get()\n        \t  File \"/usr/lib/python2.4/Queue.py\", line 119, in get\n        \t    self.not_empty.wait()\n        \t  File \"/usr/lib/python2.4/threading.py\", line 203, in wait\n        \t    waiter.acquire()\n        \n        \tThread -1295316080:\n        \t  ...\n        \n        When a thread is actually handling a web request, it's URL is written in the first line : ::\n        \n        \tThread -1303708784 (GET /++apidoc++/Interface/ztfy.app.test.test.IDocument/index.html):\n        \t  File \"/usr/lib/python2.4/threading.py\", line 442, in __bootstrap\n        \t    self.run()\n        \t  File \"/usr/lib/python2.4/threading.py\", line 422, in run\n        \t    self.__target(*self.__args, **self.__kwargs)\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 863, in worker_thread_callback\n        \t    runnable()\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1037, in <lambda>\n        \t    lambda: self.process_request_in_thread(request, client_address))\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1053, in process_request_in_thread\n        \t    self.finish_request(request, client_address)\n        \t  File \"/usr/lib/python2.4/SocketServer.py\", line 254, in finish_request\n        \t    self.RequestHandlerClass(request, client_address, self)\n        \t  File \"/usr/lib/python2.4/SocketServer.py\", line 521, in __init__\n        \t    self.handle()\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 432, in handle\n        \t    BaseHTTPRequestHandler.handle(self)\n        \t  File \"/usr/lib/python2.4/BaseHTTPServer.py\", line 316, in handle\n        \t    self.handle_one_request()\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 427, in handle_one_request\n        \t    self.wsgi_execute()\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 287, in wsgi_execute\n        \t    self.wsgi_start_response)\n        \t  File \"build/bdist.darwin-8.10.1-i386/egg/z3c/evalexception.py\", line 10, in __call__\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/evalexception/middleware.py\", line 186, in __call__\n        \t    return self.respond(environ, start_response)\n        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/evalexception/middleware.py\", line 306, in respond\n        \t    app_iter = self.application(environ, detect_start_response)\n        \t  File \"/var/local/src/ztfy/eggs/zope.app.wsgi-3.4.0-py2.4.egg/zope/app/wsgi/__init__.py\", line 54, in __call__\n        \t    request = publish(request, handle_errors=handle_errors)\n        \t  File \"/var/local/src/ztfy/eggs/tmp4szHYV/zope.publisher-3.5.0a1.dev_r78838-py2.4.egg/zope/publisher/publish.py\", line 133, in publish\n        \t  File \"/var/local/src/ztfy/eggs/tmpUIaR4E/zope.app.publication-3.4.3-py2.4.egg/zope/app/publication/zopepublication.py\", line 167, in callObject\n        \t  File \"/var/local/src/ztfy/eggs/tmp4szHYV/zope.publisher-3.5.0a1.dev_r78838-py2.4.egg/zope/publisher/publish.py\", line 108, in mapply\n        \t  File \"/var/local/src/ztfy/eggs/tmp4szHYV/zope.publisher-3.5.0a1.dev_r78838-py2.4.egg/zope/publisher/publish.py\", line 114, in debug_call\n        \t  File \"/var/local/src/ztfy/eggs/zope.app.pagetemplate-3.4.0-py2.4.egg/zope/app/pagetemplate/simpleviewclass.py\", line 44, in __call__\n        \t    return self.index(*args, **kw)\n        \t  File \"/var/local/src/ztfy/eggs/zope.app.pagetemplate-3.4.0-py2.4.egg/zope/app/pagetemplate/viewpagetemplatefile.py\", line 83, in __call__\n        \t    return self.im_func(im_self, *args, **kw)\n        \t  File \"/var/local/src/ztfy/eggs/zope.app.pagetemplate-3.4.0-py2.4.egg/zope/app/pagetemplate/viewpagetemplatefile.py\", line 51, in __call__\n        \t    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),\n        \t  File \"/var/local/src/ztfy/eggs/tmpvYYhPw/zope.pagetemplate-3.4.0-py2.4.egg/zope/pagetemplate/pagetemplate.py\", line 115, in pt_render\n        \t  File \"/var/local/src/ztfy/eggs/tmpUxe0uv/zope.tal-3.4.1-py2.4.egg/zope/tal/talinterpreter.py\", line 271, in __call__\n        \t  File \"/var/local/src/ztfy/eggs/tmpUxe0uv/zope.tal-3.4.1-py2.4.egg/zope/tal/talinterpreter.py\", line 346, in interpret\n        \t  File \"/var/local/src/ztfy/eggs/tmpUxe0uv/zope.tal-3.4.1-py2.4.egg/zope/tal/talinterpreter.py\", line 891, in do_useMacro\n        \t...\n        \n        Of course, the service is available even when each server's thread is currently busy and when\n        the server can't serve any web request.\n        \n        \n        Changelog\n        =========\n        \n        0.1\n        ---\n        - Initial release", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "http://trac.ztfy.org/ztfy.monitor", "keywords": "ZTFY Zope3 threads monitor", "license": "ZPL", "maintainer": "", "maintainer_email": "", "name": "ztfy.monitor", "package_url": "https://pypi.org/project/ztfy.monitor/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/ztfy.monitor/", "project_urls": {"Download": "UNKNOWN", "Homepage": "http://trac.ztfy.org/ztfy.monitor"}, "release_url": "https://pypi.org/project/ztfy.monitor/0.1/", "requires_dist": null, "requires_python": null, "summary": "A zc.z3monitor extension to follow Zope3 server threads activity", "version": "0.1", "yanked": false, "html_description": "<div class=\"project-description\">\n            ====================<br>        ztfy.monitor package<br>        ====================<br>        <br>        .. contents::<br>        <br>        What is ztfy.monitor ?<br>        ======================<br>        <br>        ztfy.monitor is a small monitor for Zope 3, using zc.z3monitor as base package.<br>        It adds a \"threads\" command to monitoring console, to see what the Zope server is<br>        actually doing, even when all threads are busy and the server can't respond to any request.<br>        <br>        It's actually useful when your server is not performing as well as you would like, is eating<br>        all your CPU time or is waiting in a deadlock loop.<br>        <br>        It's main code is based on DeadlockDebugger, developed by Nuxeo for the Zope2 application<br>        server.<br>        <br>        <br>        How to use ztfy.monitor ?<br>        =========================<br>        <br>        This package can be used via the zc.monitor NGI server ; read the configuration of this package to see how it is configured.<br>        <br>        Go on by including ztfy.monitor package into your application configuration : ::<br>        <br>        \t&lt;include package=\"ztfy.monitor\" /&gt;<br>        <br>        After that and as soon as the monitoring server is launched, you can connect and<br>        use the \"threads\" command to see threads activity ; for example, by using the \"netcat\"<br>        application on a monitor running on port 8081 : ::<br>        <br>        \t$ echo \"threads\" | nc localhost 8081<br>        \tThreads traceback dump at 2008-11-03 21:50:46<br>        <br>        \tThread -1210468160:<br>        \t  File \"./bin/paster\", line 151, in ?<br>        \t    paste.script.command.run()<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteScript-1.6.2-py2.4.egg/paste/script/command.py\", line 79, in run<br>        \t    invoke(command, command_name, options, args[1:])<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteScript-1.6.2-py2.4.egg/paste/script/command.py\", line 118, in invoke<br>        \t    exit_code = runner.run(args)<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteScript-1.6.2-py2.4.egg/paste/script/command.py\", line 213, in run<br>        \t    result = self.command()<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteScript-1.6.2-py2.4.egg/paste/script/serve.py\", line 257, in command<br>        \t    server(app)<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteDeploy-1.3.1-py2.4.egg/paste/deploy/loadwsgi.py\", line 139, in server_wrapper<br>        \t    wsgi_app, context.global_conf,<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/PasteDeploy-1.3.1-py2.4.egg/paste/deploy/util/fixtypeerror.py\", line 57, in fix_call<br>        \t    val = callable(*args, **kw)<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1314, in server_runner<br>        \t    serve(wsgi_app, **kwargs)<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1282, in serve<br>        \t    server.serve_forever()<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1066, in serve_forever<br>        \t    self.handle_request()<br>        \t  File \"/usr/lib/python2.4/SocketServer.py\", line 217, in handle_request<br>        \t    request, client_address = self.get_request()<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1100, in get_request<br>        \t    (conn,info) = SecureHTTPServer.get_request(self)<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 378, in get_request<br>        \t    (conn, info) = self.socket.accept()<br>        \t  File \"/usr/lib/python2.4/socket.py\", line 161, in accept<br>        \t    sock, addr = self._sock.accept()<br>        \t<br>        \tThread -1303708784:<br>        \t  File \"/usr/lib/python2.4/threading.py\", line 442, in __bootstrap<br>        \t    self.run()<br>        \t  File \"/usr/lib/python2.4/threading.py\", line 422, in run<br>        \t    self.__target(*self.__args, **self.__kwargs)<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 851, in worker_thread_callback<br>        \t    runnable = self.queue.get()<br>        \t  File \"/usr/lib/python2.4/Queue.py\", line 119, in get<br>        \t    self.not_empty.wait()<br>        \t  File \"/usr/lib/python2.4/threading.py\", line 203, in wait<br>        \t    waiter.acquire()<br>        <br>        \tThread -1295316080:<br>        \t  ...<br>        <br>        When a thread is actually handling a web request, it's URL is written in the first line : ::<br>        <br>        \tThread -1303708784 (GET /++apidoc++/Interface/ztfy.app.test.test.IDocument/index.html):<br>        \t  File \"/usr/lib/python2.4/threading.py\", line 442, in __bootstrap<br>        \t    self.run()<br>        \t  File \"/usr/lib/python2.4/threading.py\", line 422, in run<br>        \t    self.__target(*self.__args, **self.__kwargs)<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 863, in worker_thread_callback<br>        \t    runnable()<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1037, in &lt;lambda&gt;<br>        \t    lambda: self.process_request_in_thread(request, client_address))<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 1053, in process_request_in_thread<br>        \t    self.finish_request(request, client_address)<br>        \t  File \"/usr/lib/python2.4/SocketServer.py\", line 254, in finish_request<br>        \t    self.RequestHandlerClass(request, client_address, self)<br>        \t  File \"/usr/lib/python2.4/SocketServer.py\", line 521, in __init__<br>        \t    self.handle()<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 432, in handle<br>        \t    BaseHTTPRequestHandler.handle(self)<br>        \t  File \"/usr/lib/python2.4/BaseHTTPServer.py\", line 316, in handle<br>        \t    self.handle_one_request()<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 427, in handle_one_request<br>        \t    self.wsgi_execute()<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/httpserver.py\", line 287, in wsgi_execute<br>        \t    self.wsgi_start_response)<br>        \t  File \"build/bdist.darwin-8.10.1-i386/egg/z3c/evalexception.py\", line 10, in __call__<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/evalexception/middleware.py\", line 186, in __call__<br>        \t    return self.respond(environ, start_response)<br>        \t  File \"/var/local/src/ztfy/lib/python2.4/site-packages/Paste-1.6-py2.4.egg/paste/evalexception/middleware.py\", line 306, in respond<br>        \t    app_iter = self.application(environ, detect_start_response)<br>        \t  File \"/var/local/src/ztfy/eggs/zope.app.wsgi-3.4.0-py2.4.egg/zope/app/wsgi/__init__.py\", line 54, in __call__<br>        \t    request = publish(request, handle_errors=handle_errors)<br>        \t  File \"/var/local/src/ztfy/eggs/tmp4szHYV/zope.publisher-3.5.0a1.dev_r78838-py2.4.egg/zope/publisher/publish.py\", line 133, in publish<br>        \t  File \"/var/local/src/ztfy/eggs/tmpUIaR4E/zope.app.publication-3.4.3-py2.4.egg/zope/app/publication/zopepublication.py\", line 167, in callObject<br>        \t  File \"/var/local/src/ztfy/eggs/tmp4szHYV/zope.publisher-3.5.0a1.dev_r78838-py2.4.egg/zope/publisher/publish.py\", line 108, in mapply<br>        \t  File \"/var/local/src/ztfy/eggs/tmp4szHYV/zope.publisher-3.5.0a1.dev_r78838-py2.4.egg/zope/publisher/publish.py\", line 114, in debug_call<br>        \t  File \"/var/local/src/ztfy/eggs/zope.app.pagetemplate-3.4.0-py2.4.egg/zope/app/pagetemplate/simpleviewclass.py\", line 44, in __call__<br>        \t    return self.index(*args, **kw)<br>        \t  File \"/var/local/src/ztfy/eggs/zope.app.pagetemplate-3.4.0-py2.4.egg/zope/app/pagetemplate/viewpagetemplatefile.py\", line 83, in __call__<br>        \t    return self.im_func(im_self, *args, **kw)<br>        \t  File \"/var/local/src/ztfy/eggs/zope.app.pagetemplate-3.4.0-py2.4.egg/zope/app/pagetemplate/viewpagetemplatefile.py\", line 51, in __call__<br>        \t    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),<br>        \t  File \"/var/local/src/ztfy/eggs/tmpvYYhPw/zope.pagetemplate-3.4.0-py2.4.egg/zope/pagetemplate/pagetemplate.py\", line 115, in pt_render<br>        \t  File \"/var/local/src/ztfy/eggs/tmpUxe0uv/zope.tal-3.4.1-py2.4.egg/zope/tal/talinterpreter.py\", line 271, in __call__<br>        \t  File \"/var/local/src/ztfy/eggs/tmpUxe0uv/zope.tal-3.4.1-py2.4.egg/zope/tal/talinterpreter.py\", line 346, in interpret<br>        \t  File \"/var/local/src/ztfy/eggs/tmpUxe0uv/zope.tal-3.4.1-py2.4.egg/zope/tal/talinterpreter.py\", line 891, in do_useMacro<br>        \t...<br>        <br>        Of course, the service is available even when each server's thread is currently busy and when<br>        the server can't serve any web request.<br>        <br>        <br>        Changelog<br>        =========<br>        <br>        0.1<br>        ---<br>        - Initial release\n          </div>"}, "last_serial": 730562, "releases": {"0.1": [{"comment_text": "", "digests": {"md5": "364a3bb97c1ba42cc86ba8e58d006860", "sha256": "50a5a7989e28c439226df7e898a1eacaba8f68089007d863c4b646ca4e6a3600"}, "downloads": -1, "filename": "ztfy.monitor-0.1-py2.5.egg", "has_sig": false, "md5_digest": "364a3bb97c1ba42cc86ba8e58d006860", "packagetype": "bdist_egg", "python_version": "2.5", "requires_python": null, "size": 14704, "upload_time": "2010-07-25T08:52:33", "upload_time_iso_8601": "2010-07-25T08:52:33.977090Z", "url": "https://files.pythonhosted.org/packages/71/0d/16865ae69daad69bab1e5ab38d1499d66820ee5c6a64c19578857c63185b/ztfy.monitor-0.1-py2.5.egg", "yanked": false}, {"comment_text": "", "digests": {"md5": "4e9efc1abd9faac6f6a2829c25fd7f0e", "sha256": "8f300a0f31ffba742ed815fcb05d758bba9e754acc90fed4b49fd32717d3da43"}, "downloads": -1, "filename": "ztfy.monitor-0.1.tar.gz", "has_sig": false, "md5_digest": "4e9efc1abd9faac6f6a2829c25fd7f0e", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 12889, "upload_time": "2010-07-25T08:56:07", "upload_time_iso_8601": "2010-07-25T08:56:07.614219Z", "url": "https://files.pythonhosted.org/packages/3e/c1/c69668f2f254c4424f729ee1aa04b925b50c0e5b1e65df7bca411bb2c79d/ztfy.monitor-0.1.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "364a3bb97c1ba42cc86ba8e58d006860", "sha256": "50a5a7989e28c439226df7e898a1eacaba8f68089007d863c4b646ca4e6a3600"}, "downloads": -1, "filename": "ztfy.monitor-0.1-py2.5.egg", "has_sig": false, "md5_digest": "364a3bb97c1ba42cc86ba8e58d006860", "packagetype": "bdist_egg", "python_version": "2.5", "requires_python": null, "size": 14704, "upload_time": "2010-07-25T08:52:33", "upload_time_iso_8601": "2010-07-25T08:52:33.977090Z", "url": "https://files.pythonhosted.org/packages/71/0d/16865ae69daad69bab1e5ab38d1499d66820ee5c6a64c19578857c63185b/ztfy.monitor-0.1-py2.5.egg", "yanked": false}, {"comment_text": "", "digests": {"md5": "4e9efc1abd9faac6f6a2829c25fd7f0e", "sha256": "8f300a0f31ffba742ed815fcb05d758bba9e754acc90fed4b49fd32717d3da43"}, "downloads": -1, "filename": "ztfy.monitor-0.1.tar.gz", "has_sig": false, "md5_digest": "4e9efc1abd9faac6f6a2829c25fd7f0e", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 12889, "upload_time": "2010-07-25T08:56:07", "upload_time_iso_8601": "2010-07-25T08:56:07.614219Z", "url": "https://files.pythonhosted.org/packages/3e/c1/c69668f2f254c4424f729ee1aa04b925b50c0e5b1e65df7bca411bb2c79d/ztfy.monitor-0.1.tar.gz", "yanked": false}], "timestamp": "Fri May  8 03:10:41 2020"}